spring.profiles.active=local
spring.application.name=rest

spring.datasource.url=jdbc:mysql://localhost:3307/museo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.port=8081

