services:
  mysql:
    image: mysql:8.0
    container_name: museo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: museo
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    