services:
  mysql:
    image: mysql:8.0
    container_name: museo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: museo
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/02-data.sql
    